name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v1
    - name: Test compilation
      run: cargo check
    - name: Run tests
      run: cargo test
    - name: fmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy -- -D warnings
    - name: Check crate package size (feat. 'cargo diet')
      continue-on-error: true
      run: |
        curl -LSfs https://raw.githubusercontent.com/the-lean-crate/cargo-diet/master/ci/install.sh | \
         sh -s -- --git the-lean-crate/cargo-diet --target x86_64-unknown-linux-musl --tag v1.2.4

        cargo diet -n --package-size-limit 90KB
