name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*  # Trigger the action when a tag is pushed that matches this pattern

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up the repository name as an environment variable
      - name: Set repository name
        run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      # Install Rust toolchain using rustup
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      # Build the Rust project in release mode
      - name: Build the binary
        run: cargo build --release --bin $REPO_NAME

      # Read the contents of CHANGELOG.md
      - name: Read CHANGELOG.md
        id: changelog
        run: echo "CHANGELOG_CONTENT=$(cat CHANGELOG.md)" >> $GITHUB_ENV

      # Create GitHub Release with the CHANGELOG content as the release notes
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ env.REPO_NAME }}
          body: ${{ env.CHANGELOG_CONTENT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}