name: Cross-Compile with Cross

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.*  # Trigger on version tags
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu  # Use the GNU toolchain for Windows

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      # Install `cross` using cargo
      - name: Install cross
        run: cargo install cross

      # Build the project using cross for the specified target
      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      # Archive the binary as an artifact
      - name: Archive binary
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/$(basename ${{ github.repository }})* artifacts/

      # Upload the artifact for later use
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository }}-${{ matrix.target }}
          path: artifacts/*